version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "tiny11"
      RAM_SIZE: "8G"
      CPU_CORES: "6"
      DISK_SIZE: "30G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./win:/storage
      - ./tiny11.iso:/storage/custom.iso
    stop_grace_period: 2m
    restart: no
